language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.9.0
gemfile:
  - Gemfile
  - Gemfile-java

matrix: 
  exclude:
    - rvm: jruby-9.1.9.0
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile-java
    - rvm: 2.1.10
      gemfile: Gemfile-java
    - rvm: 2.2.6
      gemfile: Gemfile-java
    - rvm: 2.3.3
      gemfile: Gemfile-java
    - rvm: 2.4.0
      gemfile: Gemfile-java

notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
sudo: false
cache: bundler
services:
  - redis-server
